[project]
name = "spotify_to_tidal"
version = "1.0.4"
requires-python = ">=3.10"
readme = "readme.md"

dependencies = [
  "spotipy~=2.24.0",
  "tidalapi==0.8.8",
  "pyyaml~=6.0",
  "tqdm~=4.64",
  "sqlalchemy~=2.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-mock>=3.8",
]

# Scripts / entry points
[project.scripts]
spotify_to_tidal = "spotify_to_tidal.__main__:main"

[tool.pyright]
venvPath = "."
venv = ".venv"
reportPrivateImportUsage = "none"

[tool.uv]
package=true